apiVersion: v1
kind: Service
metadata:
  name: feed-item-svc
  labels:
    app: feed-item  
  namespace: default
  selfLink: /api/v1/namespaces/default/services/feed-item-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: feed-item
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
