apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend  
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: udagram-frontend
  type: LoadBalancer
